version: '3.8'
services:
  database: 
    image: postgres:15.0
    container_name: database
    ports:
      - 5434:5432 # { port in host (myPC) } : { port in Container }
    #environment variables, like: db's username, passwork
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:
# Create container, network, ...from "docker composer" file:
# docker compose up -d
# delete: docker compose down